# Generated by Django 5.0.1 on 2024-01-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
    ]
