# Generated by Django 5.0.1 on 2024-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_profile_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='post/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
