# Generated by Django 5.0.2 on 2024-03-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_text_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Post',
            new_name='fk_post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='User',
            new_name='fk_user',
        ),
    ]
