# Generated by Django 5.0.1 on 2024-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_profile_follower_remove_profile_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
