# Generated by Django 5.0.1 on 2024-03-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_post_follow_count_post_follower_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follow_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='follower_count',
        ),
    ]
