# Generated by Django 5.0.1 on 2024-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_post_follow_count_remove_post_follower_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='main_app.post'),
        ),
        migrations.DeleteModel(
            name='stream',
        ),
    ]
